### ISSUE TITLE
(v0.3.1) tests are not passing on python 2.7.10

### ISSUE THREAD

**Issue by Baguage** [Axiacore/py-expression-eval#10]
Just noticed this problem when running tests:

Error
```bash
Traceback (most recent call last):
  File "D:\Repositories\py-expression-eval-baguage\py_expression_eval\tests.py", line 43, in test_parser
    self.assertEqual(parser.parse('pyt(2 , 0)').evaluate({}),2)
  File "D:\Repositories\py-expression-eval-baguage\py_expression_eval\__init__.py", line 138, in evaluate
    nstack.append(apply(f, n1))
NameError: name 'apply' is not defined
```

**Comment by vero4karu** [comment]
Hello @Baguage,

What version of Python do you have?

**Comment by Baguage** [comment]
I was running tests using python 2.7.10 on Windows 10 workstation. I can try it on Linux or MAC if you can't reproduce it in your environment - lmk.

**Comment by vero4karu** [comment]
Thank you! I could reproduce it running the tests in Travis CI for different Python versions.

The problem is with  `apply()` method:

> Deprecated since version 2.3: Use function(*args, **keywords) instead of apply(function, args, keywords) (see Unpacking Argument Lists).

I'll fix  this :)

**Comment by Baguage** [comment]
awesome!

**Comment by vero4karu** [comment]
@Baguage Just uploaded a new version: https://pypi.python.org/pypi/py_expression_eval/0.3.2 and now we have tests for different Python versions https://travis-ci.org/Axiacore/py-expression-eval
