### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by bharadwaj-raju** [AxiaCore/py-expression-eval#4]
There seems to be absolutely no documentation.

There isn't even a description.

The user can't figure out what module name to `import` in Python.

**Comment by camilonova** [comment]
@ctrl-alt-delete are you willing to help on that?

**Comment by ctrl-alt-delete** [comment]
@camilonova Sure, I'll fix it

**Comment by camilonova** [comment]
@ctrl-alt-delete I just added you as collaborator to this repo as well. Thanks.
