### ISSUE TITLE
Added support for integers in hexadecimal notation

### ISSUE THREAD

**Issue by parraman** [axiacore/py-expression-eval#74]
Hi!

First of all, thank you for your work and your useful package :-)

While using it, I have stumbled with the need of parsing hexadecimal numbers. I have made the modifications to the original code myself, as well as a set of unit tests. These modifications are part of pull request #73.

I hope you find it right and useful and, if you consider it necessary, add this feature to the package.

Thank you very much in advance.

**Comment by camilonova** [comment]
Thank you. Your PR was just merged :)
